### ISSUE TITLE
Problem with Pager and ajax

### ISSUE THREAD

**Issue by nanmaniac** [Mottie/tablesorter#1836]
I have a table (#laTabla) where I import data from a database with ajax and I want to show only 25 files and have a pager. I have used Tablesorter. Data is loaded from the database but all rows are shown and the arrows are not working.
```
$('#laTabla')
        .tablesorter({
         theme : "bootstrap",
         textExtraction:{
            1: function(node, table, cellIndex) { return parseInt($(node).attr("data-order")); },
            6: function(node, table, cellIndex) { return parseInt($(node).attr("data-order")); }
         },
         widgets : [ "filter","zebra"],
         widgetOptions : {
               zebra : [ "even", "odd" ],
               filter_reset : ".reset",
               filter_cssFilter: [
                 'form-control filterHead',
                 'form-control filterHead',
                 'form-control filterHead', 
                 'form-control filterHead',
                 'form-control filterHead',
                 'form-control filterHead',
                 'form-control filterHead',
                 'form-control filterHead'
               ]
         },
         sortList: [[2,0], [1,0]] })
        .tablesorterPager({
          container: $(".pager"),
          ajaxUrl : 'loadTable2.php',
          customAjaxUrl: function(table, url) {
              $(table).trigger('changingUrl', url);
              return url;
          },
          ajaxError: null,
          ajaxObject: {
            data: paquete,
            type: 'POST', 
            dataType: 'json'
          },
          ajaxProcessing: function(data) {
              return data;
          },
          processAjaxOnInit: true,
          output: '{startRow} to {endRow} ({totalRows})',
          updateArrows: true,
          page: 0,
          size: 25,
          savePages: false,
          storageKey: 'tablesorter-pager',
          pageReset: 0,
          fixedHeight: false,
          removeRows: false,
          countChildRows: false,
          cssNext        : '.next', 
          cssPrev        : '.prev', 
          cssFirst       : '.first',
          cssLast        : '.last', 
          cssGoto        : '.gotoPage', 
          cssPageDisplay : '.pagedisplay', 
          cssPageSize    : '.pagesize', 
          cssDisabled    : 'disabled', 
          cssErrorRow    : 'tablesorter-errorRow'
        });
```
And the HTML code for the table:
```
<table id='laTabla' class='tablesorter'>
    <caption data-n='0'> items found</caption>
    <thead class='thead-dark'>
        <tr class="tablesorter-ignoreRow">
          <td class="pager" colspan="8">
            <img src="https://mottie.github.io/tablesorter/addons/pager/icons/first.png" class="first"/>
            <img src="https://mottie.github.io/tablesorter/addons/pager/icons/prev.png" class="prev"/>
            <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
            <img src="https://mottie.github.io/tablesorter/addons/pager/icons/next.png" class="next"/>
            <img src="https://mottie.github.io/tablesorter/addons/pager/icons/last.png" class="last"/>
            <select class="pagesize">
              <option value="25">25</option>
            </select>
          </td>
        </tr>
        <tr>
            <th class='sorter-false filter-false'>
                <div class='custom-control custom-checkbox'>
                    <input type='checkbox' class='custom-control-input' id='customCheck_all'>
                    <label class='custom-control-label customCheck_all' for='customCheck_all'></label>
                </div>
            </th>
            <th class='filter-select rarities'></th>
            <th data-placeholder='Search a word'>Name</th>
            <th>Family</th>
            <th>Source</th>
            <th>Level</th>
            <th>Price</th>
            <th>Traits</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
```
As I have copied the basic example there are some points of code I do not use. I think that the event where the pager works is not typed...
Can you see why Pager is not working?

**Comment by TheSin-** [comment]
arrows not showing is an indication of missed versions.  What version are you using, and where are your script include lines?

**Comment by nanmaniac** [comment]
> arrows not showing is an indication of missed versions. What version are you using, and where are your script include lines?
```
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.min.js" integrity="sha256-dtGH1XcAyKopMui5x20KnPxuGuSx9Rs6piJB/4Oqu6I=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.widgets.min.js" integrity="sha256-GxbszpUzg+iYIcyDGyNVLz9Y0dQvzmQgXXVk5cHJbw0=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/widgets/widget-pager.min.js" integrity="sha512-+X/dsto9+7foPuqwqjm+mJSPYk6Coovg9jQJvM+aBfscXOyBrAKN69GS5Z2TkMLlVHxeiE5doVqelnMfbsS9XQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

**Comment by TheSin-** [comment]
And that theme css?

**Comment by nanmaniac** [comment]
I have my own css file and these ones:
```
<link rel="shortcut icon" href="/img/logo5.png" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/css/theme.bootstrap_4.min.css" integrity="sha256-vFn0MM8utz2N3JoNzRxHXUtfCJLz5Pb9ygBY2exIaqg=" crossorigin="anonymous" />
```
Maybe some file is missing...?

**Comment by TheSin-** [comment]
it's been a while and I do not use the bootstrap theme, but I seem to remember a thing with the bootstrap theme and the arrows.

That being said it does look right, are you getting any js errors in the console?

Oh wait I know what it is, you are using Ajax, with Ajax to limits need to be done server side, your sql call should only return 25 lines, not all, TableSorter only hides on none Ajax calls.  Once you go Ajax it's all server side filters, sorting and limits.

**Comment by nanmaniac** [comment]
Ouch, I did not see that coming!
```
Uncaught TypeError: Cannot read properties of undefined (reading 'page')
    at HTMLTableElement.<anonymous> (items3.php:1437:45)
    at HTMLTableElement.dispatch (jquery-3.6.3.js:5494:27)
    at elemData.handle (jquery-3.6.3.js:5298:28)
    at Object.trigger (jquery-3.6.3.js:8829:12)
    at jQuery.fn.init.triggerHandler (jquery-3.6.3.js:8913:24)
    at widget-pager.min.js:4:14042
    ```

**Comment by TheSin-** [comment]
ahh downgrade jQuery or add jQuery migration?  Sorry I'm on very little sleep and it's been a long time since I worked on TS.

**Comment by TheSin-** [comment]
That or do you have elements hidden before population?  I've seen that cause issues as well.  I normally combat that by loading in a div out of the window view, then I move it after it's loaded.

**Comment by TheSin-** [comment]
glad you got it.

**Comment by nanmaniac** [comment]
The website is here:
https://pf2easy.com/php/tools/items3.php
Just set Rarity = rare and click Table button

**Comment by TheSin-** [comment]
again I repeat, with Ajax all sorting, filtering and limits are server side, if you return more then 25 rows then all rows are shown.

**Comment by nanmaniac** [comment]
Ouch, and.. .Is there a way to prevent showing all rows at once?
I am a little lost here

**Comment by TheSin-** [comment]
loadTable2.php returns

```
Notice: Undefined index: q in /home/nanmaniac/public_html/php/tools/loadTable2.php on line 8

Warning: mysqli::query(): Empty query in /home/nanmaniac/public_html/php/tools/loadTable2.php on line 10

Notice: Trying to get property 'num_rows' of non-object in /home/nanmaniac/public_html/php/tools/loadTable2.php on line 11

Fatal error: Uncaught Error: Call to a member function fetch_assoc() on bool in /home/nanmaniac/public_html/php/tools/loadTable2.php:61 Stack trace: #0 {main} thrown in /home/nanmaniac/public_html/php/tools/loadTable2.php on line 61
```

**Comment by TheSin-** [comment]
if you use Ajax, you need to call them by page, otherwise don't use Ajax.

If you look a the Ajax (XHR calls) you'll see the get vars you need to form your sql statement properly.

**Comment by nanmaniac** [comment]
yes, you cannot visit that website if you do not go with arguments sent by POST.
it is called with POST and the arguments are send by items3.php

**Comment by nanmaniac** [comment]
It generates a json that items3.php loads into the table

**Comment by TheSin-** [comment]
> It generates a json that items3.php loads into the table

maybe but it's not correct and it's looking for a q= which you won't get with Ajax call.  And it's returning all results, not with the right object calls.

**Comment by TheSin-** [comment]
```
<br />
<b>Notice</b>:  Trying to get property 'num_rows' of non-object in <b>/home/nanmaniac/public_html/php/tools/loadTable2.php</b> on line <b>11</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function fetch_assoc() on bool in /home/nanmaniac/public_html/php/tools/loadTable2.php:61
Stack trace:
#0 {main}
  thrown in <b>/home/nanmaniac/public_html/php/tools/loadTable2.php</b> on line <b>61</b><br />
```

see num_rows isn't set, etc etc, it's just retuning all rows, which is no good its not what Ajax pager needs.

**Comment by nanmaniac** [comment]
I typed at The last line of loadTable2.php:
```
echo json_encode(['total_rows' => $totalN, 'rows' => $tbody]);
```

**Comment by nanmaniac** [comment]
where $tbody is an array of arrays (the rows) and $totalN is the total number of rows

**Comment by nanmaniac** [comment]
I really appreciate the time you are giving to me. But in the items3.php tablesorter options there are some lines where I called Ajax:
```ajaxObject: {
            data: paquete,
            type: 'POST', 
            dataType: 'json'
          }
``` Where paquete sends q to the loadTable.php

**Comment by TheSin-** [comment]
what is total_rows? you aren't following the documentation, it's num_rows

**Comment by nanmaniac** [comment]
> what is total_rows? you aren't following the documentation, it's num_rows

I changed to num_rows and json is loaded to the table, but Pager is not acting. I think that maybe I do not have good documentation. It would be nice if pointed me where I might find that documentation

**Comment by TheSin-** [comment]
it must not be live cause I'm still seeing the num_rows error.

**Comment by TheSin-** [comment]
https://mottie.github.io/tablesorter/docs/example-widget-pager-ajax.html

**Comment by TheSin-** [comment]
Look slike I lead you wrong in php you shoudl return

`json_encode(array(count($total_rows), rows => array($rows 1 to 25)));`

**Comment by TheSin-** [comment]
oh wait, you are loading the pager widget, but your javascript is initializing the pager add-on, they are different.  Move your setup to the widget block and drop the `.tablesorterPager` or load the pager add-on and remove the pager widget.

**Comment by nanmaniac** [comment]
Ypu are right now I see that I copied a previous code I have, the real one (that loads the table for me) is:
```
$('#laTabla')
					.tablesorter({
					 theme : "bootstrap",
					 textExtraction:{
					 	1: function(node, table, cellIndex) { return parseInt($(node).attr("data-order")); },
					 	6: function(node, table, cellIndex) { return parseInt($(node).attr("data-order")); }
					 },
					 widgets : [ "filter","zebra","pager"],
					 widgetOptions : {
					       zebra : [ "even", "odd" ],
					       // reset filters button
					       filter_reset : ".reset",
					       // extra css class name (string or array) added to the filter element (input or select)
					       filter_cssFilter: [
					         'form-control filterHead',
					         'form-control filterHead',
					         'form-control filterHead', // select needs custom class names :(
					         'form-control filterHead',
					         'form-control filterHead',
					         'form-control filterHead',
					         'form-control filterHead',
					         'form-control filterHead'
					       ],
					       pager_css: {
			                 container   : 'tablesorter-pager',
			                 errorRow    : 'tablesorter-errorRow', // error information row (don't include period at beginning)
			                 disabled    : 'disabled'              // class added to arrows @ extremes (i.e. prev/first arrows "disabled" on first page)
			               },
			               pager_selectors: {
	                         container   : '.pager',       // target the pager markup (wrapper)
	                         first       : '.first',       // go to first page arrow
	                         prev        : '.prev',        // previous page arrow
	                         next        : '.next',        // next page arrow
	                         last        : '.last',        // go to last page arrow
	                         gotoPage    : '.gotoPage',    // go to page selector - select dropdown that sets the current page
	                         pageDisplay : '.pagedisplay', // location of where the "output" is displayed
	                         pageSize    : '.pagesize'     // page size selector - select dropdown that sets the "size" option

	                       },
	                       pager_output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', //'{startRow} to {endRow} of {totalRows} rows', // '{page}/{totalPages}'
	                       // apply disabled classname to the pager arrows when the rows at either extreme is visible
                           pager_updateArrows: true,

                           // starting page of the pager (zero based index)
                           pager_startPage: 0,

                           // Reset pager to this page after filtering; set to desired page number
                           // (zero-based index), or false to not change page at filter start
                           pager_pageReset: 0,

                           // Number of visible rows
                           pager_size: 25,

                           // f true, child rows will be counted towards the pager set size
                           pager_countChildRows: false,

                           // Save pager page & size if the storage script is loaded (requires $.tablesorter.storage in jquery.tablesorter.widgets.js)
                           pager_savePages: true,

                           // Saves tablesorter paging to custom key if defined. Key parameter name
                           // used by the $.tablesorter.storage function. Useful if you have
                           // multiple tables defined
                           pager_storageKey: "tablesorter-pager",

                           // if true, the table will remain the same height no matter how many records are displayed. The space is made up by an empty
                           // table row set to a height to compensate; default is false
                           pager_fixedHeight: false,

                           // remove rows from the table to speed up the sort of large tables.
                           // setting this to false, only hides the non-visible rows; needed if you plan to add/remove rows with the pager enabled.
                           pager_removeRows: false, // removing rows in larger tables speeds up the sort
                           pager_ajaxUrl: 'loadTable2.php?{filterList:filter}&{sortList:column}',
                           pager_ajaxError: null,

                           // modify the $.ajax object to allow complete control over your ajax requests
                           pager_ajaxObject: {
                             data: paquete,
                             type: 'POST', // default setting
                             dataType: 'json'
                           },

                           // Set this option to false if your table data is preloaded into the
                           // table, but you are still using ajax
                           pager_processAjaxOnInit: true,

                           // When processAjaxOnInit is set to false, set this option to contain
                           // the total number of rows and filtered rows to prevent an initial ajax
                           // call
                           initialRows: {
                             total: 100,
                             filtered: 100
                           },
                           pager_ajaxProcessing: function(data) {
                             return data;
                           }
					 },
					 sortList: [[2,0], [1,0]] });
```

**Comment by TheSin-** [comment]
yeah now you are using the widget.

make sure you add `{page}` and `{size}` to this so you know how to form your sql statement

`pager_ajaxUrl: 'loadTable2.php?{filterList:filter}&{sortList:column}',`

to

`pager_ajaxUrl: 'loadTable2.php?{filterList:filter}&{sortList:column}&page={page}&limit={size}',`

**Comment by nanmaniac** [comment]
I think I am not getting it. Why filterlist from the tablesorter should affect mysql query? The php sends always ALL rows...
I think that you are telling me that the wuery within the loadTable2.php should change with the values sent with `{filterList:filter}&{sortList:column}&page={page}&limit={size}`. Am I right?

**Comment by TheSin-** [comment]
it's just how you want to send the info.  like that is fine, then you need parsers in php, this code will only kinda make sense, but something like this

```
	public static function SSSorter($fields, $colClasses) {
		$sorts = array();

		// Sorting
		// $val 0 = ASC, 1 = DESC
		foreach ($_GET['col'] as $col => $val) {
			$direction = "ASC";
			if (!empty($val))
				$direction = "DESC";

			$classes = explode(' ', $colClasses[$col]);

			$sorter = false;
			if (count($classes) > 0)
				foreach ($classes as $class)
					if (preg_match('/^sorter-(.*)/', $class, $matches))
						if ($matches[1] != 'false')
							$sorter = $matches[1] . "Parser";

			if (!empty($sorter))
				array_push($sorts, TableSorter::$sorter('sql', $direction, $fields[$col]));
			else
				array_push($sorts, $fields[$col] . ' ' . $direction);
		}

		return " ORDER BY " . implode(", ", $sorts);
	}

	public static function SSFilter($fields, $colClasses) {
		$checks = array();

		foreach ($_GET['fcol'] as $col => $val) {
			$classes = explode(' ', $colClasses[$col]);

			$sorter = false;
			$filters = array();
			$is_date = false;
			if (count($classes) > 0) {
				foreach ($classes as $class) {
					if (preg_match('/^sorter-(.*)/', $class, $matches))
						if ($matches[1] != 'false')
							$sorter = $matches[1] . "Parser";
					if (preg_match('/^filter-(.*)/', $class, $matches))
						if ($matches[1] != 'false')
							$filters[] = $matches[1];
					if (preg_match('/^is_date$/', $class))
						$is_date = true;
					if (preg_match('/^is_price$/', $class)) {
						$val = preg_replace('/^\$ /', '', $val);
						$val = preg_replace('/,/', '', $val);
					}
				}
			}

			$field = $fields[$col];
			if (!empty($sorter)) {
				list($regex, $replace) = TableSorter::$sorter('regex');
				if (!empty($regex))
					$val = "REGEX" . $regex . " " . preg_replace('/' . $regex . '/', $replace, $val);
			}

			if (in_array('select', $filters) ||
			    in_array('exact', $filters))
				array_push($checks, TableSorter::processFilters($field, "=" . $val, $is_date));
			else
				array_push($checks, TableSorter::processFilters($field, $val, $is_date));
		}

		return $checks;
	}
```

And you need to use $_GET['size'] and $_GET['limit'] to set the. Something like

```
        $limit = '';
        if (isset($_GET['ajax']) && $_GET['ajax']) {
                $start = $_GET['page'] * $_GET['limit'];
                $limit = $_GET['limit'];
        } else {
                $start = 0;
                $limit = 25;
        }
        $limit = " LIMIT ${start}, ${limit}";
```

**Comment by TheSin-** [comment]
that's the issue, when you use Ajax you can NOT send all rows, table sorter won't do the work when Ajax is used

If you are sending all rows there is no point in using Ajax at that point.  Just send them all at the start and turn off Ajax, let table sorter deal with it.  The issue is for tables that have thousands or rows with lots of cols, that is a slow initial load, so send the info in chucks via Ajax calls is much faster.

you need to determine if you need Ajax or if you are going to do a full load on start.  If you want to full load then don't use Ajax it's a waste.

**Comment by nanmaniac** [comment]
Aaah, So the query I send to the database has to be edited with those arguments.... Ok ok I Think that I am going to figure it out. Oh thank you

**Comment by TheSin-** [comment]
basically Ajax = everything done server side, filtering, sorting, and pages, and nothing is done client side (javascript) so only send what you want to display

if you want it all done client side don't use Ajax.

**Comment by TheSin-** [comment]
no problem, enjoy
